In [1]:
import torch
import numpy as np
from torch import autograd

In [2]:
x=torch.empty(2,2)
x

tensor([[0., 0.],
        [0., 0.]])

### 自动求导

In [15]:
x = torch.tensor(1.)
a=torch.tensor(1.,requires_grad=True)
b=torch.tensor(2.,requires_grad=True)
c=torch.tensor(3.,requires_grad=True)

y=a**2*x+b*x+c

In [16]:
print(a.grad,b.grad,c.grad)
grads=autograd.grad(y,[a,b,c])
print(grads[0],grads[1],grads[2])

None None None
tensor(2.) tensor(1.) tensor(1.)


In [17]:
print(y.grad_fn)

In [18]:
# out.backward()

In [22]:
a.data

tensor(1.)

In [23]:
a

tensor(1., requires_grad=True)

In [24]:
a.grad

In [25]:
a.item()

1.0

In [26]:
a.is_leaf

True

In [9]:
# x = torch.tensor([5,3])

x = torch.Tensor([5,3])
x

tensor([5., 3.])

In [10]:
x.shape

torch.Size([2])

In [11]:
x.size()

torch.Size([2])

### opreation

In [15]:
x = torch.rand(5,3)
y = torch.rand(5,3)
x+y

tensor([[1.4460, 1.5842, 1.0019],
        [1.1808, 0.8283, 0.4683],
        [1.1044, 0.7817, 1.5490],
        [1.0942, 0.5845, 0.5583],
        [0.8208, 1.4000, 1.3799]])

In [16]:
torch.add(x,y)

tensor([[1.4460, 1.5842, 1.0019],
        [1.1808, 0.8283, 0.4683],
        [1.1044, 0.7817, 1.5490],
        [1.0942, 0.5845, 0.5583],
        [0.8208, 1.4000, 1.3799]])

In [17]:
z = torch.add(x,y)
z

tensor([[1.4460, 1.5842, 1.0019],
        [1.1808, 0.8283, 0.4683],
        [1.1044, 0.7817, 1.5490],
        [1.0942, 0.5845, 0.5583],
        [0.8208, 1.4000, 1.3799]])

In [18]:
result = torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[1.4460, 1.5842, 1.0019],
        [1.1808, 0.8283, 0.4683],
        [1.1044, 0.7817, 1.5490],
        [1.0942, 0.5845, 0.5583],
        [0.8208, 1.4000, 1.3799]])

In [19]:
x

tensor([[0.9825, 0.6625, 0.5247],
        [0.7461, 0.0309, 0.1871],
        [0.6709, 0.3645, 0.8224],
        [0.9575, 0.3199, 0.2049],
        [0.2290, 0.9804, 0.4750]])

In [22]:
x[:,1]

tensor([0.6625, 0.0309, 0.3645, 0.3199, 0.9804])

In [29]:
# xx= x.view(15)
xx= x.view(-1,5)
xx

tensor([[0.9825, 0.6625, 0.5247, 0.7461, 0.0309],
        [0.1871, 0.6709, 0.3645, 0.8224, 0.9575],
        [0.3199, 0.2049, 0.2290, 0.9804, 0.4750]])

In [51]:
x= torch.tensor([1,2])
y= torch.tensor([3,4])
z=x.add(y)
z

tensor([4, 6])

In [52]:
torch.eye(2,2)

tensor([[1., 0.],
        [0., 1.]])

In [54]:
torch.linspace(1,10,4)

tensor([ 1.,  4.,  7., 10.])

In [57]:
x

tensor([1, 2])

In [56]:
index = torch.LongTensor([0,1,1])
torch.gather(x,0,index)

tensor([1, 2, 2])

### 图

In [27]:
x = torch.tensor(1.)
a=torch.tensor(1.,requires_grad=True)
b=torch.tensor(2.,requires_grad=True)
c=torch.tensor(3.,requires_grad=True)

y=a**2*x+b*x+c

In [28]:
y

tensor(6., grad_fn=<AddBackward0>)

In [29]:
y.is_leaf

False

In [53]:
x = torch.tensor([2.,2.],requires_grad=True)

In [54]:
y = x+1

In [55]:
def fun(y):
    return (y**2).sum()

In [56]:
z = fun(y)

In [57]:
z

tensor(18., grad_fn=<SumBackward0>)

In [48]:
z.backward(retain_graph=True)

In [50]:
x.grad

tensor([6., 6.])

In [58]:
y.sum().backward(retain_graph=True)

In [59]:
x.grad

tensor([1., 1.])

### neural