In [1]:
import numpy as np
import pandas as pd
import sklearn
import torch

from torch.utils.data import DataLoader
from torchvision import transforms
from torchvision import datasets
import torch.nn.functional as F
import torch.nn as nn
import torch.optim as optim

In [2]:
batch_size=1
seq_len=3
input_size=4
hidden_size=2

In [6]:
cell = torch.nn.RNNCell(input_size=input_size,hidden_size=hidden_size)
dataset=torch.randn(seq_len,batch_size,input_size)
hidden=torch.zeros(batch_size,hidden_size)

for idx, input  in enumerate(dataset):
    print('='*20,idx,'='*20)
    print('input size:',input.shape)
    hidden=cell(input,hidden)
    print('outputs size:',hidden.shape)
    print(hidden)

==================== 0 ====================
input size: torch.Size([1, 4])
outputs size: torch.Size([1, 2])
tensor([[ 0.0964, -0.0458]], grad_fn=<TanhBackward>)
==================== 1 ====================
input size: torch.Size([1, 4])
outputs size: torch.Size([1, 2])
tensor([[-0.7504, -0.8917]], grad_fn=<TanhBackward>)
==================== 2 ====================
input size: torch.Size([1, 4])
outputs size: torch.Size([1, 2])
tensor([[-0.0356, -0.7497]], grad_fn=<TanhBackward>)
